package me.whereareiam.identica.common.config.defaults;

import me.whereareiam.identica.common.config.defaults.messages.MessagesDefaults;
import me.whereareiam.identica.model.config.Messages;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

@DisplayName("Messages Defaults")
class MessagesDefaultsTest {
	@DisplayName("Provider restriction messages are generated by defaults")
	@Test
	void providerRestrictionMessagesAreGeneratedByDefaults() {
		Messages messages = new MessagesDefaults().supply(new Messages());

		assertNotNull(messages.getEngine());
		assertNotNull(messages.getEngine().getPrepare());
	}
}
