package me.whereareiam.identica.type.migration;

public enum MigrationResultStatus {
	PENDING_CONFIRMATION,
	PENDING_EXISTS,
	NO_PENDING,
	EXPIRED,
	CANCELLED,
	STARTED,
	ALREADY_PRIMARY,
	PRIMARY_SET,
	TARGET_UNSUPPORTED,
	PROVIDER_UNAVAILABLE,
	PRECHECK_DENIED,
	FAILED
}
