package me.whereareiam.identica.type.verification;

public enum VerificationActionStatus {
	STARTED,
	PENDING_CODE,
	PENDING_SAVED_CONFIRMATION,
	ACTIVATED,
	UPDATED,
	DISABLED,
	CANCELLED,
	RESET,
	NO_PENDING,
	UNKNOWN_METHOD,
	ALREADY_ENROLLED,
	METHOD_NOT_ENROLLED,
	METHOD_UNAVAILABLE,
	INVALID_CODE,
	REQUIRES_SAVED_CONFIRMATION,
	NOT_ALLOWED
}
